### ISSUE TITLE
[BUG] missing mods and if mod exist another crash errors

### ISSUE THREAD

**Issue by Blazzycrafter** [LunarLoony/The-Minehattan-Project#3]
the missing mod is fusion needed by rechiseled
crash log: [https://mclo.gs/RSQAj6N](https://mclo.gs/RSQAj6N)

if i install it manual...
the game does show nothing...
its simply Crashed
https://mclo.gs/XN8qhqy

**Comment by Blazzycrafter** [comment]
oh and i use ATLauncher if you wanna ask XD

**Comment by LunarLoony** [comment]
Thanks for reporting - strange that Fusion didn't come up as a dependency. Never mind.
I have created a new version which adds Fusion, but that seems to also have broken a variety of other things! Think I'll open a new issue for that.
Will be fixed in version **5.0.3**
