### ISSUE TITLE
[BUG] Macaw's Bridges - Invocation Target Exception - v5.0.5

### ISSUE THREAD

**Issue by Willt125** [LunarLoony/The-Minehattan-Project#5]
Upon updating the modpack (through PollyMC), I can no longer load Minecraft.

Macaw's Bridges is throwing java.lang.reflect.InvocationTargetException: null, at first over Iron Stairs.
I attempted to re-download MB-BYG directly from forge, and it throws the same error, except about the Support Pillar.
I believe teeechnically it was throwing warnings on the previous version (5.0.4), but it wasn't breaking anything to my awareness at that time, since I hadn't reached a point where I was using those blocks.

Support files follow:
[crash-2024-05-02_09.37.33-fml_censored.txt](https://github.com/LunarLoony/The-Minehattan-Project/files/15189198/crash-2024-05-02_09.37.33-fml_censored.txt)
[latest_censored.log](https://github.com/LunarLoony/The-Minehattan-Project/files/15189199/latest_censored.log)

If you need any further information I'll do my best to be prompt!

**Comment by MasterGamer64** [comment]
Did you manage to find a fix? I am running into the same issue on 5.0.5.

**Comment by TigerWalts** [comment]
Updating **Macaw's Bridges - Oh The Biomes You'll Go** to version **1.4** fixes this

- https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go/files/5256720

**Comment by LunarLoony** [comment]
Hi all, thanks for your patience. I've updated the pack with the new version of the mod. Seems to be working okay for me, or at least it doesn't immediately crash this time.

Will update the Modrinth version soon as well.

@TigerWalts thankyou for finding a fix.
